#!/usr/bin/env bash
# Regenerates Hearth-Tests/src/Shaders.h from Hearth-Tests/shaders/*.
#
# The tests carry their SPIR-V as arrays rather than loading .spv files. That keeps them
# hermetic: `Hearth-Tests` needs no glslc, no working directory and no assets on disk, which
# is what lets the suite run on a bare CI box against lavapipe. Run this after editing any
# shader under Hearth-Tests/shaders.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/Hearth-Tests/shaders"
OUT="$ROOT/Hearth-Tests/src/Shaders.h"

command -v glslc >/dev/null || { echo "glslc not found (shaderc)" >&2; exit 1; }

{
    echo "#pragma once"
    echo
    echo "// GENERATED by scripts/EmbedShaders.sh -- do not edit."
    echo "// Sources live in Hearth-Tests/shaders/."
    echo
    echo "#include <cstdint>"
    echo
    echo "namespace hearth::tests {"
    echo
    for shader in "$SRC"/*.vert "$SRC"/*.frag "$SRC"/*.comp; do
        [ -e "$shader" ] || continue
        base="$(basename "$shader")"
        # flat.vert -> kFlatVert
        name="k$(echo "${base%.*}" | sed -E 's/(^|_)([a-z])/\U\2/g')$(echo "${base##*.}" | sed -E 's/^(.)/\U\1/')"
        tmp="$(mktemp)"
        glslc -O "$shader" -o "$tmp"
        echo "    // $base"
        echo "    inline constexpr std::uint32_t ${name}[] = {"
        od -An -tx4 -v "$tmp" | awk '{for(i=1;i<=NF;i++) printf "0x%s, ", $i}' | fold -s -w 84 \
            | sed -E 's/^/        /; s/[[:space:]]+$//'
        echo "    };"
        echo
        rm -f "$tmp"
    done
    echo "}"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
